services:
  frontend:
    build:
      context: ./ReactFront
      dockerfile: dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./ReactBack
      dockerfile: dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - ./ReactBack:/app # Mount local files to the container
