# React Frontend Dockerfile
FROM node:16 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the Vite application
RUN npm run build

# List the contents of /app/build to check if the build directory exists
RUN ls -al /app/dist

# Serve the app using a static server
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
